#!/usr/bin/env python3
"""
Train the contextual TCN v2 residual neural network.

The model keeps the v3 idea:

    residual = clean_delta - noisy_delta
    filtered_delta = noisy_delta + predicted_residual

but the input contains contextual features generated by:

    python/pipeline/5_generate_input_dataset_context_v1.py

Only the first three input columns are base deltas: dx, dy, dz.

This version splits the model into two additive branches:

    fast_residual = local short-context branch
    slow_residual = dilated TCN slow branch
    residual = fast_residual + slow_residual

The training model exposes total, fast, and slow residual channels so the loss
can penalize local residual error, accumulated trajectory error, and slow-branch
roughness. The saved inference model only outputs the final three residual
channels expected by GPX filters.
"""

import argparse
import json
import os
import random
import time
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.layers import Activation, Add, Concatenate, Conv1D, Dense, Dropout, Input, LayerNormalization, SpatialDropout1D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam


SCRIPT_DIR = Path(__file__).resolve().parent
MODEL_TAG = "context_tcn_v2"
DELTA_FEATURES = ["dx", "dy", "dz"]
LAMBDA_TRAJ = 0.001
LAMBDA_SLOW_SMOOTH = 0.01


physical_devices = tf.config.list_physical_devices("GPU")
if physical_devices:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
    print(f"GPU available: {physical_devices[0]}")
else:
    print("Training on CPU")


class ContextTrackDataset:
    """Dataset loader for contextual pre-split GPS track data."""

    def __init__(self, data_dir="data/input_context_v1"):
        self.data_dir = Path(data_dir)
        self.train_manifest_path = self.data_dir / "train" / "manifest_train.csv"
        self.val_manifest_path = self.data_dir / "val" / "manifest_val.csv"
        self.test_manifest_path = self.data_dir / "test" / "manifest_test.csv"
        self.norm_stats_path = self.data_dir / "norm_stats_train.json"

        required_files = [
            self.train_manifest_path,
            self.val_manifest_path,
            self.test_manifest_path,
            self.norm_stats_path,
        ]
        missing_files = [path for path in required_files if not path.exists()]
        if missing_files:
            raise FileNotFoundError(f"Missing files: {missing_files}")

        with open(self.norm_stats_path, "r", encoding="utf-8") as f:
            self.norm_stats = json.load(f)

        self.input_features = self.norm_stats.get("input_features")
        if not self.input_features:
            self.input_features = None
        self.label_features = self.norm_stats.get("label_features", DELTA_FEATURES)

        print(f"Context dataset loaded from {data_dir}")
        print(f"  - Stats: {self.norm_stats_path}")
        print(f"  - Input features: {self.input_features or 'from CSV columns'}")
        print(f"  - Label features: {self.label_features}")

    def _normalize_manifest_paths(self, manifest_df):
        """Normalize path separators for cross-platform compatibility."""
        for col in ["slice_path", "label_path", "mask_path"]:
            if col in manifest_df.columns:
                manifest_df[col] = manifest_df[col].fillna("").astype(str).apply(lambda p: p.replace("\\", "/"))

    def load_by_sets(self):
        """Load train, validation, and test splits."""
        train_manifest = pd.read_csv(self.train_manifest_path)
        val_manifest = pd.read_csv(self.val_manifest_path)
        test_manifest = pd.read_csv(self.test_manifest_path)

        self._normalize_manifest_paths(train_manifest)
        self._normalize_manifest_paths(val_manifest)
        self._normalize_manifest_paths(test_manifest)

        print("Loading contextual data by split:")
        print(f"  Train: {len(train_manifest)} windows")
        print(f"  Val: {len(val_manifest)} windows")
        print(f"  Test: {len(test_manifest)} windows")

        X_train, y_train, masks_train = self._load_data_batch(train_manifest)
        X_val, y_val, masks_val = self._load_data_batch(val_manifest)
        X_test, y_test, masks_test = self._load_data_batch(test_manifest)

        if len(X_train) == 0:
            raise ValueError("Could not load training data")
        if len(X_val) == 0:
            raise ValueError("Could not load validation data")
        if len(X_test) == 0:
            raise ValueError("Could not load test data")

        print(f"Data loaded - Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")
        return (X_train, y_train, masks_train), (X_val, y_val, masks_val), (X_test, y_test, masks_test)

    def load_window_data(self, row):
        """Load one contextual window."""
        def _to_path(value):
            pstr = str(value).replace("\\", "/")
            return Path(pstr).expanduser()

        input_data = pd.read_csv(_to_path(row["slice_path"]))
        label_data = pd.read_csv(_to_path(row["label_path"]))
        mask_data = pd.read_csv(_to_path(row["mask_path"]))

        input_features = self.input_features
        if input_features is None:
            input_features = [col for col in input_data.columns if col != "time"]

        missing_input = [col for col in input_features if col not in input_data.columns]
        missing_label = [col for col in self.label_features if col not in label_data.columns]
        if missing_input:
            raise ValueError(f"Missing input columns {missing_input} in {row['slice_path']}")
        if missing_label:
            raise ValueError(f"Missing label columns {missing_label} in {row['label_path']}")

        X = input_data[input_features].to_numpy(dtype=np.float32)
        y = label_data[self.label_features].to_numpy(dtype=np.float32)
        mask = mask_data["mask"].to_numpy(dtype=np.float32)
        return X, y, mask

    def _load_data_batch(self, manifest_subset):
        """Load a complete split from a manifest."""
        X_list, y_list, masks_list = [], [], []
        for _, row in manifest_subset.iterrows():
            try:
                X, y, mask = self.load_window_data(row)
                X_list.append(X)
                y_list.append(y)
                masks_list.append(mask)
            except Exception as exc:
                print(f"Error loading window {row['slice_path']}: {exc}")

        return np.array(X_list), np.array(y_list), np.array(masks_list)


def split_training_output(y_pred):
    """Split training output into total, fast, and slow residual channels."""
    total_residual = y_pred[..., 0:3]
    fast_residual = y_pred[..., 3:6]
    slow_residual = y_pred[..., 6:9]
    return total_residual, fast_residual, slow_residual


def two_branch_residual_loss(y_true, y_pred):
    """Per-timestep loss for total residual, trajectory drift, and slow smoothness."""
    total_residual, _, slow_residual = split_training_output(y_pred)

    residual_mae = tf.reduce_mean(tf.abs(total_residual - y_true), axis=-1)

    trajectory_error = tf.cumsum(total_residual - y_true, axis=1)
    trajectory_mae = tf.reduce_mean(tf.abs(trajectory_error), axis=-1)

    slow_diff = slow_residual[:, 1:, :] - slow_residual[:, :-1, :]
    slow_smooth = tf.reduce_mean(tf.abs(slow_diff), axis=-1)
    slow_smooth = tf.pad(slow_smooth, [[0, 0], [1, 0]])

    return residual_mae + LAMBDA_TRAJ * trajectory_mae + LAMBDA_SLOW_SMOOTH * slow_smooth


def total_residual_mae_metric(y_true, y_pred):
    """Per-timestep MAE over the summed residual correction channels."""
    total_residual, _, _ = split_training_output(y_pred)
    return tf.reduce_mean(tf.abs(total_residual - y_true), axis=-1)


def trajectory_mae_metric(y_true, y_pred):
    """Per-timestep accumulated trajectory error metric in normalized units."""
    total_residual, _, _ = split_training_output(y_pred)
    trajectory_error = tf.cumsum(total_residual - y_true, axis=1)
    return tf.reduce_mean(tf.abs(trajectory_error), axis=-1)


def slow_smooth_metric(y_true, y_pred):
    """Per-timestep smoothness metric for the slow residual branch."""
    _, _, slow_residual = split_training_output(y_pred)
    slow_diff = slow_residual[:, 1:, :] - slow_residual[:, :-1, :]
    smooth = tf.reduce_mean(tf.abs(slow_diff), axis=-1)
    return tf.pad(smooth, [[0, 0], [1, 0]])


def tcn_block(x, filters, kernel_size, dilation_rate, dropout_rate):
    """Build one residual dilated temporal convolution block."""
    residual = x
    y = Conv1D(
        filters,
        kernel_size,
        padding="same",
        dilation_rate=dilation_rate,
        activation=None,
    )(x)
    y = LayerNormalization()(y)
    y = Activation("relu")(y)
    y = SpatialDropout1D(dropout_rate)(y)
    y = Conv1D(filters, 1, padding="same", activation=None)(y)
    y = LayerNormalization()(y)
    y = Add()([residual, y])
    return Activation("relu")(y)


def local_branch(inputs, output_features):
    """Create the short-context branch for fast local residual corrections."""
    x = Conv1D(64, 5, padding="same", activation=None, name="fast_conv1")(inputs)
    x = LayerNormalization(name="fast_norm1")(x)
    x = Activation("relu", name="fast_relu1")(x)
    x = Conv1D(64, 3, padding="same", activation=None, name="fast_conv2")(x)
    x = LayerNormalization(name="fast_norm2")(x)
    x = Activation("relu", name="fast_relu2")(x)
    x = Dense(32, activation="relu", name="fast_dense")(x)
    return Dense(output_features, activation="linear", name="fast_residual")(x)


def slow_branch(inputs, output_features):
    """Create the dilated TCN branch for slow residual corrections."""
    x = Conv1D(64, 1, padding="same", activation=None, name="slow_projection")(inputs)
    x = LayerNormalization(name="slow_projection_norm")(x)
    x = Activation("relu", name="slow_projection_relu")(x)

    for dilation_rate in [1, 2, 4, 8, 16, 32, 64, 128]:
        x = tcn_block(
            x,
            filters=64,
            kernel_size=5,
            dilation_rate=dilation_rate,
            dropout_rate=0.1,
        )

    x = Dense(64, activation="relu", name="slow_dense")(x)
    x = Dropout(0.2, name="slow_dropout")(x)
    return Dense(output_features, activation="linear", name="slow_residual")(x)


def create_models(sequence_length=3600, n_features=15, output_features=3):
    """Create training and inference models for the contextual TCN v2."""
    inputs = Input(shape=(sequence_length, n_features))
    fast_residual = local_branch(inputs, output_features)
    slow_residual = slow_branch(inputs, output_features)
    total_residual = Add(name="total_residual")([fast_residual, slow_residual])

    training_output = Concatenate(name="training_output")([total_residual, fast_residual, slow_residual])
    training_model = Model(inputs=inputs, outputs=training_output, name=f"{MODEL_TAG}_training")
    inference_model = Model(inputs=inputs, outputs=total_residual, name=MODEL_TAG)
    return training_model, inference_model


def plot_training_history(history, save_path):
    """Save a training history plot."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    ax1.plot(history.history["loss"], label="Train Loss")
    ax1.plot(history.history["val_loss"], label="Val Loss")
    ax1.set_title("Context TCN v2 Model Loss")
    ax1.set_xlabel("Epoch")
    ax1.set_ylabel("Loss")
    ax1.legend()
    ax1.grid(True)

    lr_key = "lr" if "lr" in history.history else "learning_rate" if "learning_rate" in history.history else None
    if lr_key:
        ax2.plot(history.history[lr_key], label="Learning Rate")
        ax2.set_title("Learning Rate")
        ax2.set_xlabel("Epoch")
        ax2.set_ylabel("LR")
        ax2.set_yscale("log")
        ax2.legend()
        ax2.grid(True)
    else:
        ax2.text(0.5, 0.5, "No LR data", ha="center", va="center", transform=ax2.transAxes)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"Plot saved to: {save_path}")


def denormalize_deltas(values, norm_stats):
    """Denormalize dx, dy, dz values."""
    out = values.copy()
    for i, feature in enumerate(DELTA_FEATURES):
        out[..., i] = out[..., i] * norm_stats["std"][feature] + norm_stats["mean"][feature]
    return out


def calculate_drift_metrics(y_pred_meters, y_test_meters, masks_test):
    """Compute spatial drift metrics by integrating deltas into positions."""
    valid_mask = masks_test.astype(bool)
    y_pred_masked = y_pred_meters.copy()
    y_test_masked = y_test_meters.copy()

    for i in range(y_pred_meters.shape[0]):
        y_pred_masked[i, ~valid_mask[i], :] = 0
        y_test_masked[i, ~valid_mask[i], :] = 0

    pos_pred = np.cumsum(y_pred_masked, axis=1)
    pos_true = np.cumsum(y_test_masked, axis=1)

    final_drifts = []
    final_z_errors = []
    all_drifts = []
    all_z_errors = []
    length_diffs = []
    pred_total_lengths = []
    true_total_lengths = []

    for i in range(pos_pred.shape[0]):
        valid_times = np.where(valid_mask[i])[0]
        if len(valid_times) == 0:
            continue

        last_valid_t = valid_times[-1]
        final_drifts.append(float(np.linalg.norm(pos_pred[i, last_valid_t, :2] - pos_true[i, last_valid_t, :2])))
        final_z_errors.append(float(pos_pred[i, last_valid_t, 2] - pos_true[i, last_valid_t, 2]))

        drift_xy = np.linalg.norm(pos_pred[i, valid_times, :2] - pos_true[i, valid_times, :2], axis=1)
        z_error = pos_pred[i, valid_times, 2] - pos_true[i, valid_times, 2]
        all_drifts.extend(drift_xy.tolist())
        all_z_errors.extend(z_error.tolist())

        pred_lengths = np.linalg.norm(y_pred_masked[i, valid_times, :2], axis=1)
        true_lengths = np.linalg.norm(y_test_masked[i, valid_times, :2], axis=1)
        pred_total = float(np.sum(pred_lengths))
        true_total = float(np.sum(true_lengths))
        length_diffs.append(abs(pred_total - true_total))
        pred_total_lengths.append(pred_total)
        true_total_lengths.append(true_total)

    drift_final_mean_m = float(np.mean(final_drifts)) if final_drifts else 0.0
    z_final_mean_m = float(np.mean(final_z_errors)) if final_z_errors else 0.0
    z_final_abs_mean_m = float(np.mean(np.abs(final_z_errors))) if final_z_errors else 0.0
    drift_rms_m = float(np.sqrt(np.mean(np.square(all_drifts)))) if all_drifts else 0.0
    z_rms_m = float(np.sqrt(np.mean(np.square(all_z_errors)))) if all_z_errors else 0.0
    length_diff_m = float(np.mean(length_diffs)) if length_diffs else 0.0
    pred_length_mean_m = float(np.mean(pred_total_lengths)) if pred_total_lengths else 0.0
    true_length_mean_m = float(np.mean(true_total_lengths)) if true_total_lengths else 0.0

    length_diff_pct = (length_diff_m / true_length_mean_m * 100.0) if true_length_mean_m > 0 else 0.0
    drift_final_pct = (drift_final_mean_m / true_length_mean_m * 100.0) if true_length_mean_m > 0 else 0.0
    drift_rms_pct = (drift_rms_m / true_length_mean_m * 100.0) if true_length_mean_m > 0 else 0.0

    return {
        "drift_final_mean_m": drift_final_mean_m,
        "drift_rms_m": drift_rms_m,
        "drift_final_xy_mean_m": drift_final_mean_m,
        "drift_rms_xy_m": drift_rms_m,
        "z_final_mean_m": z_final_mean_m,
        "z_final_abs_mean_m": z_final_abs_mean_m,
        "z_rms_m": z_rms_m,
        "length_diff_m": length_diff_m,
        "length_diff_xy_m": length_diff_m,
        "pred_length_mean_m": pred_length_mean_m,
        "true_length_mean_m": true_length_mean_m,
        "length_diff_pct": length_diff_pct,
        "length_diff_xy_pct": length_diff_pct,
        "drift_final_pct": drift_final_pct,
        "drift_rms_pct": drift_rms_pct,
        "drift_final_xy_pct": drift_final_pct,
        "drift_rms_xy_pct": drift_rms_pct,
    }


def evaluate_model(model, X_test, y_test, masks_test, norm_stats):
    """Evaluate residual predictions using only the first three input features as base deltas."""
    print("\n=== CONTEXT TCN v2 MODEL EVALUATION ===")
    residual_pred = model.predict(X_test, batch_size=32, verbose=1)
    base_delta = X_test[:, :, :3]
    y_pred = base_delta + residual_pred

    valid_positions = masks_test.astype(bool)
    y_valid = y_test[valid_positions]
    pred_valid = y_pred[valid_positions]

    mae_dx_norm = float(np.mean(np.abs(y_valid[:, 0] - pred_valid[:, 0])))
    mae_dy_norm = float(np.mean(np.abs(y_valid[:, 1] - pred_valid[:, 1])))
    mae_dz_norm = float(np.mean(np.abs(y_valid[:, 2] - pred_valid[:, 2])))
    xy_step_error_norm = np.linalg.norm(y_valid[:, :2] - pred_valid[:, :2], axis=1)
    mae_xy_norm = float(np.mean(xy_step_error_norm))
    rmse_xy_norm = float(np.sqrt(np.mean(xy_step_error_norm**2)))
    rmse_z_norm = float(np.sqrt(np.mean((y_valid[:, 2] - pred_valid[:, 2]) ** 2)))
    mae_total_norm = float(np.mean([mae_dx_norm, mae_dy_norm, mae_dz_norm]))

    print(f"MAE dx (normalized): {mae_dx_norm:.6f}")
    print(f"MAE dy (normalized): {mae_dy_norm:.6f}")
    print(f"MAE XY step (normalized): {mae_xy_norm:.6f}")
    print(f"RMSE XY step (normalized): {rmse_xy_norm:.6f}")
    print(f"MAE dz (normalized): {mae_dz_norm:.6f}")
    print(f"RMSE z (normalized): {rmse_z_norm:.6f}")
    print(f"MAE total (normalized): {mae_total_norm:.6f}")

    y_pred_meters = denormalize_deltas(y_pred, norm_stats)
    y_test_meters = denormalize_deltas(y_test, norm_stats)
    y_valid_m = y_test_meters[valid_positions]
    pred_valid_m = y_pred_meters[valid_positions]

    mae_dx_meters = float(np.mean(np.abs(y_valid_m[:, 0] - pred_valid_m[:, 0])))
    mae_dy_meters = float(np.mean(np.abs(y_valid_m[:, 1] - pred_valid_m[:, 1])))
    mae_dz_meters = float(np.mean(np.abs(y_valid_m[:, 2] - pred_valid_m[:, 2])))
    xy_step_error_meters = np.linalg.norm(y_valid_m[:, :2] - pred_valid_m[:, :2], axis=1)
    mae_xy_meters = float(np.mean(xy_step_error_meters))
    rmse_xy_meters = float(np.sqrt(np.mean(xy_step_error_meters**2)))
    rmse_z_meters = float(np.sqrt(np.mean((y_valid_m[:, 2] - pred_valid_m[:, 2]) ** 2)))
    mae_total_meters = float(np.mean([mae_dx_meters, mae_dy_meters, mae_dz_meters]))

    print(f"\nMAE dx (meters): {mae_dx_meters:.4f} m")
    print(f"MAE dy (meters): {mae_dy_meters:.4f} m")
    print(f"MAE XY step (meters): {mae_xy_meters:.4f} m")
    print(f"RMSE XY step (meters): {rmse_xy_meters:.4f} m")
    print(f"MAE dz (meters): {mae_dz_meters:.4f} m")
    print(f"RMSE z (meters): {rmse_z_meters:.4f} m")
    print(f"MAE total (meters): {mae_total_meters:.4f} m")

    drift_metrics = calculate_drift_metrics(y_pred_meters, y_test_meters, masks_test)
    drift_metrics = {key: float(value) for key, value in drift_metrics.items()}

    print("\n=== SPATIAL DRIFT METRICS ===")
    print(f"Mean final drift: {drift_metrics['drift_final_mean_m']:.4f} m")
    print(f"RMS drift: {drift_metrics['drift_rms_m']:.4f} m")
    print(f"Trajectory length difference: {drift_metrics['length_diff_m']:.4f} m")
    print(f"Relative final drift: {drift_metrics['drift_final_pct']:.2f}%")
    print(f"Relative RMS drift: {drift_metrics['drift_rms_pct']:.2f}%")

    results = {
        "mae_dx_norm": mae_dx_norm,
        "mae_dy_norm": mae_dy_norm,
        "mae_dz_norm": mae_dz_norm,
        "mae_xy_norm": mae_xy_norm,
        "rmse_xy_norm": rmse_xy_norm,
        "rmse_z_norm": rmse_z_norm,
        "mae_total_norm": mae_total_norm,
        "mae_dx_meters": mae_dx_meters,
        "mae_dy_meters": mae_dy_meters,
        "mae_dz_meters": mae_dz_meters,
        "mae_xy_meters": mae_xy_meters,
        "rmse_xy_meters": rmse_xy_meters,
        "rmse_z_meters": rmse_z_meters,
        "mae_total_meters": mae_total_meters,
        "residual_training": True,
    }
    results.update(drift_metrics)
    return results


def train_model(dataset, model_config, fast_mode=False):
    """Train contextual residual model."""
    print("\n=== CONTEXT TCN v2 NEURAL NETWORK TRAINING ===")
    (X_train, y_train, masks_train), (X_val, y_val, masks_val), (X_test, y_test, masks_test) = dataset.load_by_sets()

    if fast_mode:
        print("FAST MODE: limiting contextual data")
        max_samples = 100
        if len(X_train) > max_samples:
            indices = np.random.choice(len(X_train), max_samples, replace=False)
            X_train, y_train, masks_train = X_train[indices], y_train[indices], masks_train[indices]
        if len(X_val) > max_samples // 4:
            indices = np.random.choice(len(X_val), max_samples // 4, replace=False)
            X_val, y_val, masks_val = X_val[indices], y_val[indices], masks_val[indices]
        if len(X_test) > max_samples // 4:
            indices = np.random.choice(len(X_test), max_samples // 4, replace=False)
            X_test, y_test, masks_test = X_test[indices], y_test[indices], masks_test[indices]
        print(f"Limited data - Train: {X_train.shape[0]}, Val: {X_val.shape[0]}, Test: {X_test.shape[0]}")

    y_train_residual = y_train - X_train[:, :, :3]
    y_val_residual = y_val - X_val[:, :, :3]

    model, inference_model = create_models(sequence_length=X_train.shape[1], n_features=X_train.shape[2], output_features=3)
    model.compile(
        optimizer=Adam(learning_rate=model_config["learning_rate"]),
        loss=two_branch_residual_loss,
        metrics=[total_residual_mae_metric, trajectory_mae_metric, slow_smooth_metric],
    )

    print("Model created:")
    print(f"  - Sequence: {X_train.shape[1]} timesteps")
    print(f"  - Input features: {X_train.shape[2]}")
    print("  - Training output features: 9 (total, fast, slow residual)")
    print("  - Inference output features: 3")
    print("  - Mode: two-branch residual (output = clean_delta - noisy_delta)")
    print(f"  - Lambda trajectory: {LAMBDA_TRAJ}")
    print(f"  - Lambda slow smooth: {LAMBDA_SLOW_SMOOTH}")

    os.makedirs("models", exist_ok=True)
    callbacks = [
        EarlyStopping(monitor="val_loss", patience=model_config["patience"], restore_best_weights=True, verbose=1),
        ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=7, min_lr=1e-6, verbose=1),
    ]

    start_time = time.time()
    history = model.fit(
        X_train,
        y_train_residual,
        sample_weight=masks_train,
        batch_size=model_config["batch_size"],
        epochs=model_config["epochs"],
        validation_data=(X_val, y_val_residual, masks_val),
        callbacks=callbacks,
        verbose=1,
    )
    training_time = time.time() - start_time

    print("\nTraining completed:")
    print(f"  - Epochs trained: {len(history.history['loss'])}/{model_config['epochs']}")
    print(f"  - Total time: {training_time / 60:.2f} minutes")
    print(f"  - Final train loss: {history.history['loss'][-1]:.6f}")
    print(f"  - Final val loss: {history.history['val_loss'][-1]:.6f}")

    results_dir = Path("results") / "training"
    results_dir.mkdir(parents=True, exist_ok=True)
    plot_training_history(history, str(results_dir / f"training_history_{MODEL_TAG}.png"))

    print("\nEvaluating on TEST split...")
    test_metrics = evaluate_model(inference_model, X_test, y_test, masks_test, dataset.norm_stats)

    final_model_path = f"models/model_final_{MODEL_TAG}.keras"
    inference_model.save(final_model_path)
    print(f"Final model saved to: {final_model_path}")

    final_weights_path = f"models/model_final_{MODEL_TAG}.weights.h5"
    inference_model.save_weights(final_weights_path)
    print(f"Final model weights saved to: {final_weights_path}")

    return inference_model, history, test_metrics, training_time


def parse_args():
    parser = argparse.ArgumentParser(
        description="Train a contextual GPS correction neural network",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--data_root", default="data/input_context_v1", help="Context dataset root")
    parser.add_argument("--epochs", type=int, default=100, help="Maximum number of epochs")
    parser.add_argument("--batch_size", type=int, default=64, help="Batch size")
    parser.add_argument("--lr", type=float, default=1e-3, help="Initial learning rate")
    parser.add_argument("--patience", type=int, default=15, help="Early stopping patience")
    parser.add_argument("--fast", action="store_true", help="Fast mode for quick checks")
    parser.add_argument("--seed", type=int, default=42, help="Seed for reproducible comparisons")
    return parser.parse_args()


def main():
    print("=== GPS CONTEXT TCN v2 RESIDUAL MODEL TRAINING ===\n")
    try:
        args = parse_args()
        random.seed(args.seed)
        np.random.seed(args.seed)
        tf.keras.utils.set_random_seed(args.seed)

        model_config = {
            "epochs": args.epochs,
            "batch_size": args.batch_size,
            "learning_rate": args.lr,
            "patience": args.patience,
            "lambda_traj": LAMBDA_TRAJ,
            "lambda_slow_smooth": LAMBDA_SLOW_SMOOTH,
        }
        if args.fast:
            print("FAST MODE ENABLED")
            model_config["epochs"] = min(model_config["epochs"], 10)
            model_config["batch_size"] = min(model_config["batch_size"], 16)
            model_config["patience"] = min(model_config["patience"], 5)

        print("Configuration:")
        print(f"  - Data directory: {args.data_root}")
        print(f"  - Epochs: {model_config['epochs']}")
        print(f"  - Batch size: {model_config['batch_size']}")
        print(f"  - Learning rate: {model_config['learning_rate']}")
        print(f"  - Patience: {model_config['patience']}")
        print(f"  - Seed: {args.seed}")

        dataset = ContextTrackDataset(data_dir=args.data_root)
        _, history, test_metrics, training_time = train_model(dataset, model_config, fast_mode=args.fast)

        mode_suffix = "_fast" if args.fast else "_complete"
        results_dir = Path("results") / "training"
        results_dir.mkdir(parents=True, exist_ok=True)
        results_file = results_dir / f"training_results_{MODEL_TAG}{mode_suffix}.json"

        results = {
            "config": model_config,
            "model_type": "contextual_two_branch_tcn_residual",
            "model_tag": MODEL_TAG,
            "input_features": dataset.input_features,
            "label_features": dataset.label_features,
            "test_metrics": test_metrics,
            "training_time_minutes": training_time / 60,
            "epochs_trained": len(history.history["loss"]),
            "final_train_loss": float(history.history["loss"][-1]),
            "final_val_loss": float(history.history["val_loss"][-1]),
        }
        with open(results_file, "w", encoding="utf-8") as f:
            json.dump(results, f, indent=2)

        print("\n=== FINAL RESULTS ===")
        print(f"Mode: {'FAST' if args.fast else 'FULL'}")
        print(f"MAE total (meters): {test_metrics['mae_total_meters']:.4f} m")
        print(f"Mean final XY drift: {test_metrics['drift_final_mean_m']:.4f} m")
        print(f"RMS XY drift: {test_metrics['drift_rms_m']:.4f} m")
        print(f"Total time: {training_time / 60:.2f} minutes")
        print(f"Results saved to: {results_file}")
        return 0
    except Exception as exc:
        print(f"ERROR: {exc}")
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
