#!/usr/bin/env python3
"""
Filter a GPX track with the contextual v1 residual neural model.

The model expects the same input features generated by:

    python/pipeline/5_generate_input_dataset_context_v1.py

It predicts residual corrections for normalized dx, dy, dz only.
"""

import argparse
import importlib.util
import json
import sys
from pathlib import Path

import numpy as np
from tensorflow.keras.layers import Dense, Dropout, LSTM, Masking
from tensorflow.keras.models import Sequential


SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
CONTEXT_DATASET_SCRIPT = PROJECT_ROOT / "python" / "pipeline" / "5_generate_input_dataset_context_v1.py"
BASE_FILTER_SCRIPT = SCRIPT_DIR / "7_nn_filter.py"
DELTA_FEATURES = ["dx", "dy", "dz"]


def load_module(name, path):
    """Load a Python script as a module."""
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


context_features = load_module("context_dataset_v1", CONTEXT_DATASET_SCRIPT)
base_filter = load_module("nn_filter_base", BASE_FILTER_SCRIPT)


def create_context_model(sequence_length=3600, n_features=15, output_features=3):
    """Create the contextual LSTM residual model used during training."""
    return Sequential(
        [
            Masking(mask_value=0.0, input_shape=(sequence_length, n_features)),
            LSTM(128, return_sequences=True, dropout=0.1, recurrent_dropout=0.0),
            Dense(64, activation="relu"),
            Dropout(0.2),
            Dense(output_features, activation="linear"),
        ]
    )


def default_weights_path(model_path):
    """Return the final weights path associated with a Keras model path."""
    path = Path(model_path)
    if path.name.endswith(".keras"):
        return path.with_name(path.name[:-6] + ".weights.h5")
    return path


def load_context_model(model_path, n_features, max_sequence):
    """Load the contextual LSTM model, falling back to architecture plus weights."""
    try:
        return base_filter.load_model_robust(model_path)
    except Exception as exc:
        weights_path = default_weights_path(model_path)
        if not weights_path.exists():
            raise FileNotFoundError(
                f"Could not load {model_path} and weights file was not found: {weights_path}"
            ) from exc

        print(f"Falling back to context architecture plus weights: {weights_path}")
        model = create_context_model(sequence_length=max_sequence, n_features=n_features)
        model.load_weights(str(weights_path))
        return model

def normalize_feature_frame(feature_frame, norm_stats, input_features):
    """Normalize the contextual input features with train statistics."""
    missing = [col for col in input_features if col not in feature_frame.columns]
    if missing:
        raise ValueError(f"Missing computed input features: {missing}")

    normalized = np.zeros((len(feature_frame), len(input_features)), dtype=np.float32)
    for i, col in enumerate(input_features):
        mean = norm_stats["mean"].get(col, 0.0)
        std = norm_stats["std"].get(col, 1.0)
        values = feature_frame[col].to_numpy(dtype=np.float64)
        normalized[:, i] = 0.0 if std <= 1e-12 else (values - mean) / std
    return normalized


def denormalize_delta_channels(delta_norm, norm_stats):
    """Denormalize normalized dx, dy, dz channels."""
    delta = delta_norm.copy()
    for i, feature in enumerate(DELTA_FEATURES):
        delta[:, i] = delta[:, i] * norm_stats["std"][feature] + norm_stats["mean"][feature]
    return delta


def apply_context_filter(
    track_df,
    model_path="models/model_final_context_v1.keras",
    norm_stats_path="data/input_context_v1/norm_stats_train.json",
    model_output="residual",
    max_sequence=3600,
    model_loader=None,
):
    """Apply the contextual residual neural filter to a parsed GPX DataFrame."""
    print("Loading contextual normalization statistics...")
    with open(norm_stats_path, "r", encoding="utf-8") as f:
        norm_stats = json.load(f)

    input_features = norm_stats.get("input_features")
    if not input_features:
        raise ValueError("Context norm stats must include input_features")

    print(f"Input features: {input_features}")
    if model_loader is None:
        model = load_context_model(model_path, len(input_features), max_sequence)
    else:
        model = model_loader(model_path, len(input_features), max_sequence)

    print("Setting up geodesic projection...")
    lat_center = track_df["lat"].mean()
    lon_center = track_df["lon"].mean()
    transformer = base_filter.setup_projection(lat_center, lon_center)

    lat_ref = track_df["lat"].iloc[0]
    lon_ref = track_df["lon"].iloc[0]
    x, y = base_filter.latlon_to_meters(track_df["lat"], track_df["lon"], transformer, lat_ref, lon_ref)
    z = track_df["ele"].to_numpy(dtype=np.float64)

    print("Calculating base deltas...")
    dx, dy, dz = base_filter.calculate_deltas(x, y, z)

    print("Building contextual features...")
    feature_frame = context_features.build_feature_frame(dx, dy, dz, x, y)
    input_matrix = normalize_feature_frame(feature_frame, norm_stats, input_features)

    sequence_length = len(input_matrix)
    print(f"Processing {sequence_length} points in chunks of {max_sequence}")

    filtered_chunks = []
    for i in range(0, sequence_length, max_sequence):
        end_idx = min(i + max_sequence, sequence_length)
        chunk_len = end_idx - i

        input_data = np.zeros((1, max_sequence, len(input_features)), dtype=np.float32)
        input_data[0, :chunk_len, :] = input_matrix[i:end_idx, :]

        model_chunk = model.predict(input_data, verbose=0)
        if model_output == "residual":
            filtered_chunk = input_data[:, :, :3] + model_chunk
        elif model_output == "direct":
            filtered_chunk = model_chunk
        else:
            raise ValueError(f"Unsupported model output mode: {model_output}")

        filtered_chunks.append(filtered_chunk[0, :chunk_len, :])

    filtered_norm = np.vstack(filtered_chunks)
    filtered_delta = denormalize_delta_channels(filtered_norm, norm_stats)

    print("Integrating filtered deltas...")
    x_filt, y_filt, z_filt = base_filter.integrate_deltas(
        filtered_delta[:, 0],
        filtered_delta[:, 1],
        filtered_delta[:, 2],
        x[0],
        y[0],
        z[0],
    )

    print("Converting back to lat/lon...")
    lat_filt, lon_filt = base_filter.meters_to_latlon(x_filt, y_filt, transformer, lat_ref, lon_ref)

    filtered_df = track_df.copy()
    filtered_df["lat"] = lat_filt
    filtered_df["lon"] = lon_filt
    filtered_df["ele"] = z_filt

    print("Position preservation check:")
    print(f"  Original: ({track_df['lat'].iloc[0]:.8f}, {track_df['lon'].iloc[0]:.8f})")
    print(f"  Filtered: ({filtered_df['lat'].iloc[0]:.8f}, {filtered_df['lon'].iloc[0]:.8f})")
    return filtered_df


def parse_args(
    default_model="models/model_final_context_v1.keras",
    default_suffix="nn_context_v1_filtered",
    description="Filter GPS track using contextual neural network",
):
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument("input_gpx", help="Input GPX file")
    parser.add_argument("output_gpx", nargs="?", help="Output filtered GPX file")
    parser.add_argument("--model", default=default_model, help="Path to trained context model")
    parser.add_argument(
        "--norm-stats",
        default="data/input_context_v1/norm_stats_train.json",
        help="Path to contextual normalization statistics",
    )
    parser.add_argument("--model-output", choices=["residual", "direct"], default="residual")
    parser.add_argument("--max-sequence", type=int, default=3600, help="Chunk length used by the model")
    parser.add_argument("--suffix", default=default_suffix, help="Suffix for auto-generated output filename")
    return parser.parse_args()


def main(
    default_model="models/model_final_context_v1.keras",
    default_suffix="nn_context_v1_filtered",
    description="Filter GPS track using contextual neural network",
    model_loader=None,
):
    args = parse_args(
        default_model=default_model,
        default_suffix=default_suffix,
        description=description,
    )

    try:
        if args.output_gpx is None:
            input_path = Path(args.input_gpx)
            args.output_gpx = input_path.parent / f"{input_path.stem}_{args.suffix}{input_path.suffix}"
            print(f"Output file auto-generated: {args.output_gpx}")
        else:
            Path(args.output_gpx).parent.mkdir(parents=True, exist_ok=True)

        print(f"Processing {args.input_gpx}...")
        track_df = base_filter.parse_gpx(args.input_gpx)
        filtered_df = apply_context_filter(
            track_df,
            model_path=args.model,
            norm_stats_path=args.norm_stats,
            model_output=args.model_output,
            max_sequence=args.max_sequence,
            model_loader=model_loader,
        )

        base_filter.create_gpx_with_gpxpy(
            filtered_df["lat"],
            filtered_df["lon"],
            filtered_df["ele"],
            filtered_df["time"] if "time" in filtered_df.columns else None,
            str(args.output_gpx),
        )

        print("SUCCESS: Context filtering completed")
        print(f"   Input: {len(track_df)} points")
        print(f"   Output: {len(filtered_df)} points")
        return 0
    except Exception as exc:
        print(f"ERROR: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
